### ISSUE TITLE
Synchronize pantsu wearing

### ISSUE THREAD

**Issue by diemjo** [diemjo/patriot#7]

**Comment by Joopon** [comment]
when regenerating pantsu: is onPlayerTick event executed on every client or only on client with corresponding player? Otherwise too many messages will be sent to the server... and server will send messages to itself...
(probably executed on all players, because otherwise it wouldn't have updated on the other players in earlier versions and pantsu would never have regenerated)
Better when everyone counts for all players themselfs? Or every player counts only for himself and informs the other players?
